### ISSUE TITLE
Close HTML tags

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/teach-people-to-code#5]
Currently the course doesn't tell students to close tags such as `img` and `input`.

## Expected

`<img src="shiba-inu.jpg"/>`

## What I see

`<img src="shuba=inu.jpg">`

**Comment by richardTowers** [comment]
This is actually deliberate. Technically, `<img>` is a "void" element, so it doesn't need to be closed.

You could well say that it's better to use a self-closing tag (`<img/>`) anyway, and then you're compatible with XHTML. There are some confusing edge cases I'd prefer to try and avoid though.

Consider:

* We explain to people that `<tag/>` is shorthand for `<tag></tag>` (i.e. an empty element)
* We explain that it's better to use `<img/>` for images and the other void elements.

That's all well and good, but someone might think to themselves "I won't bother with the shorthand, I'll do `<img></img>`" - that's actually *wrong* though - img is a void element, so it can't have a closing tag. Browsers treat that as two separate images (in my experience).

Alternatively, people might think to themselves "It's inefficient to write `<script src="..."></script>` when I could just write `<script src="..."/>`" only that's wrong too! `<script>` isn't a void element, so it can't be self-closing.

In the end, you end up having to explain void elements anyway, so you may as well explain that they don't need closing.

I think it's better just to ignore the whole sorry situation until someone is getting fairly serious about writing HTML though, which is why it isn't mentioned.

**Comment by richardTowers** [comment]
Here's someone's blog that explains it better:

https://hackernoon.com/to-close-or-not-to-close-4365d24853ff

**Comment by lfdebrux** [comment]
That's interesting, I did not fully appreciate the intricacies of self-closing tags myself. Thanks for the write-up, you're right, saying it's a void tag and doesn't need to be closed does make it easier.

It is quite an experience to see someone coming to HTML for the first time and seeing them spot all the inconsistencies and idiosyncrasies that we've learnt to look past...
